version: '2'
services:
  sentry_wsgi:
    restart: always
    image: ilyahumbar/sentry
    container_name: sentry
    env_file: sentry-env
    depends_on:
      - postgres
      - redis
      - memcached
      - sentry_celery
      - sentry_celery_beat
    ports:
      - "9000:9000"
    volumes:
      - ./data/sentry:/var/lib/sentry/files
  sentry_celery:
    restart: always
    image: ilyahumbar/sentry
    container_name: sentry-celery
    env_file: sentry-env
    command: run worker
    depends_on:
      - postgres
      - redis
      - memcached
  sentry_celery_beat:
    restart: always
    image: ilyahumbar/sentry
    container_name: sentry-celery-beat
    env_file: sentry-env
    command: run cron
    working_dir: /tmp
    depends_on:
      - postgres
      - redis
      - memcached
  sentry_upgrade_db:
    image: ilyahumbar/sentry
    env_file: sentry-env
    command: upgrade --noinput
    depends_on:
      - postgres
      - redis
      - memcached
  memcached:
    restart: always
    image: memcached
    container_name: memcached
  redis:
    restart: always
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    container_name: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  postgres:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=sentry 
      - POSTGRES_USER=sentry
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
